[package]
name = "rs_ray_tracing_v2"
version = "0.1.0"
authors = ["Arlo Blythe"]
edition = "2021"
rust-version = "1.56"

[dependencies]
eframe = "0.17.0"
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
rand = "0.8.5"
rand_distr = "0.4.3"
wgpu = "0.12.0"
bytemuck = "1.9.1"
env_logger = "0.9.0"
pollster = "0.2.5"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2
