[package]
name = "rs_ray_tracing_v3"
version = "0.1.0"
authors = ["Arlo Blythe"]
edition = "2021"

# The window just doesn't open with opt-level = 0
# No clue why

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 2

[dependencies]
egui-latest_wgpu_backend = "0.18.0"
egui = "0.18.1"
egui-winit = "0.18.0"
rand = "0.8.5"
rand_distr = "0.4.3"
wgpu = { version = "0.12.0", features = ["spirv"] }
inline-spirv = "0.1.4"
pollster = "0.2.5"
num_cpus = "1.13.1"
winit = "0.26.1"
image = { version = "0.24.1", default-features = false, features = ["openexr"] }
uuid = { version = "1.0.0", features = ["v4"] }

