[package]
name = "rs_ray_tracing_v3"
version = "0.1.0"
authors = ["Arlo Blythe"]
edition = "2021"
rust-version = "1.60"

[dependencies]
eframe = "0.17.0"
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
rand = "0.8.5"
rand_distr = "0.4.3"
wgpu = "0.12.0"
bytemuck = "1.9.1"
env_logger = "0.9.0"
pollster = "0.2.5"
num_cpus = "1.13.1"
winit = "0.26.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "epaint_image_draw"
harness = false

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2
